//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPOE.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_reservacion
    {
        public int idDetalle { get; set; }
        public Nullable<int> idReservacion { get; set; }
        public Nullable<int> idPasajero { get; set; }
    }
}
