//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPOE.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sivarviajesEntities : DbContext
    {
        public sivarviajesEntities()
            : base("name=sivarviajesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalle_reservacion> detalle_reservacion { get; set; }
        public virtual DbSet<pasajero> pasajero { get; set; }
        public virtual DbSet<reservacion> reservacion { get; set; }
        public virtual DbSet<vuelo> vuelo { get; set; }
    }
}
