//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPOE.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuelo
    {
        public int idVuelo { get; set; }
        public string aerolinea { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
        public Nullable<System.TimeSpan> hora_llegada { get; set; }
        public Nullable<int> asientos { get; set; }
        public Nullable<double> costoVuelo { get; set; }
    }
}
